<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tuitorial</title>
    <link rel=icon href=logo.jpg sizes="16x16" type="image/png">
    <link rel="stylesheet" href="guide.css">


</head>
<body>
    <h2>Guide</h2>
    <embed class = "video" src ='tuitorial\full.mp4.mp4' width ='750' height = '400'> </embed>
    <form action="start.php" method="POST">
        <button class="btn" value="home" type="submit">Home </button>

    </form>

</body>
</html>